package com.ebuy.userservice.embedded;

public enum Privilege {
    VENDORS_READ_PRIVILEGE,
    VENDORS_WRITE_PRIVILEGE,
    SUPPLIERS_READ_PRIVILEGE,
    SUPPLIERS_WRITE_PRIVILEGE,
    USER_GROUPS_READ_PRIVILEGE,
    USER_GROUPS_WRITE_PRIVILEGE,
    USER_SEGMENTS_READ_PRIVILEGE,
    USER_SEGMENTS_WRITE_PRIVILEGE,
    USERS_READ_PRIVILEGE,
    USERS_WRITE_PRIVILEGE,
    MESSAGES_READ_PRIVILEGE,
    MESSAGES_WRITE_PRIVILEGE
}